# Generated by Django 3.2 on 2021-04-30 12:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 30, 12, 32, 0, 513787, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mail',
            name='send_from',
            field=models.CharField(max_length=100),
        ),
    ]
