# Generated by Django 3.2 on 2021-04-30 12:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0002_auto_20210430_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 30, 12, 51, 8, 414938, tzinfo=utc)),
        ),
    ]
