# Generated by Django 3.2 on 2021-05-01 04:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0003_alter_mail_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='passcode',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mail',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 1, 4, 9, 2, 808406, tzinfo=utc)),
        ),
    ]
