# Generated by Django 3.2 on 2021-05-03 11:11

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0004_auto_20210501_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='nonce',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mail',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 11, 11, 8, 715625, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mail',
            name='passcode',
            field=models.CharField(blank=True, default='', max_length=100, validators=[django.core.validators.RegexValidator(code='nomatch', message='The pass code must have exactly 8 characters', regex='^.{8}$| ')]),
        ),
        migrations.AlterField(
            model_name='mail',
            name='send_from',
            field=models.CharField(max_length=100, verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='send_to',
            field=models.CharField(max_length=100, verbose_name='To'),
        ),
    ]
